### ISSUE TITLE
An error when running the file 'demo-data-guv.py'.

### ISSUE THREAD

**Issue by ghost** [talonchandler/polaris#1]
The file 'demo-data-guv.py' cannot be executed and it has an error 'TypeError: lake_response() takes 1 positional argument but 2 were given'. However, I can run ‘demo-synthetic-helix.py’ correctly. 
Is there an error in file 'multi.py' or it's caused by some of my reasons? Thanks!
<img width="682" alt="TypeError" src="https://user-images.githubusercontent.com/103934976/163800775-679c699d-c340-4cee-896d-243470644e5f.PNG">

**Comment by talonchandler** [comment]
Hi Junyu, 

Thanks for reporting! My apologies that this repository isn't very sophisticated (no automated tests, etc), so I've accidentally let that script lapse. I will very likely have time in the next week to fix this properly, but in the meantime you're welcome to comment out the calibration lines (like the one that throwing an error now) to see what happens. 

I'll post here when I fix it. 

All the best!

**Comment by talonchandler** [comment]
Fix is now on `main`. Thanks for your patience and interest.
